# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [6]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)
A.dtype


dtype('int32')

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)
# Stores dimension, shape, size and datatype of A in dict below
a_dict = dict(dimension = A.ndim,
             shape = A.shape, 
             size = A.size,
             datatype = A.dtype.name)

# Prints key-value pairs
print(f"Below are the characteristics of our matrix A:")
print(A)
for key, value in a_dict.items():
    print(f"{key}: {value}")

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print(C)
print("Elementwise subtraction (B-C):\n",
      B-C)
print("Elementwise multiplication (B*C):\n",
      B*C)
print("Matrix multiplication (B x C):\n",
      B@C)

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

# Below for test
# B = np.array([[44,88,3,5], [5, 99,30,300], [10, 45, 71, 101], [97, 75, 16, 1]])
# print(B)

# np.unravel_index(B.argmin(axis=1), B.shape)

In [ ]:


# Assumes that the calculations always should start on the original matrix.

#Exponentiate each number elementwise (use the np.exp function).
print("Each element in matrix calculated with np.exp: \n",
      np.exp(B)) # Each number in the matrix exponentiated

# Calculate the minimum value in the whole matrix.
print("Minimum value in B: \n",
      np.min(B)) # Minimum value in B

# Calculcate the minimum value in each row.
print("Minimum value in each row: \n",
      np.min(B, axis=1)) # Minimum values in each row

#Calculcate the minimum value in each column.
print("Minimum value in each column: \n",
      np.min(B, axis=0)) # Minimum values in each column 

#Find the index value for the minimum value in the whole matrix 
# Below i used some numpy functions to enable correct dimension of the indexes
print("Index in B for smallest value: \n",
      np.unravel_index(np.argmin(B), B.shape)) # Minimum values in each column. B.argmin() gives index in 1D. 
                                             # Works nice on multi-dimensional arrays too


# Find the index value for the minimum value in each row
col_idx = np.argmin(B, axis=1) # retrieve column index for min values of each row
print(col_idx)
row_idx = np.arange(B.shape[0]) # generates the row indexes from B
idx = list(zip(row_idx, col_idx))

print("Index of minimum value for each row:\n",
     idx)

# Calculate the sum for all elements.
print("The sum for all elements in B is:\n",
    np.sum(B))

# Calculate the mean for each column.
print("The mean for each column in B is:\n",
    np.mean(B, axis=0))

# Calculate the median for each column.
print("The median for each column in B is:\n",
    np.median(B, axis=0))

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

**In this case, A is a two dimensional array.
So if we only gives a number as above (A[1]) it returns the first dimensions corresponding elements.
In this case, dim 0 is rows, and 1 corresponds to row 2 -> The second row is returned from array A.
For e.g. multidimensional array X with shape (10x40x3x5) X[1] would return the second block (dim=0), 40x3x5 (40 sets of 3x5 matrixes).
By using ":" to specify dimension, we can extract what we want, e.g. X[:, 0] gives the first matrix in each of the 40 sets.**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
for i in A:
    print(i)


[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [16]:
# One way would be to do a for-loop with respect to the shape of A
for row in range(A.shape[0]):
    for col in range(A.shape[1]):
        print(A[row, col])

# Approach above not good for elementwise iterations - many dimensions leads to nested for-loops

# We can use numpys flat-attribute:
for element in A.flat:
    print(element)
    
# We can use numpys ravel() method:
for element in A.ravel():
    print(element)

# We can use numpys nditer() method:
for element in np.nditer(A):
    print(element)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [22]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print(b)

b.mean(axis=1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


array([[ 5.,  6.,  7.,  8.,  9.],
       [20., 21., 22., 23., 24.]])

**a is here a 1x30 array. reshape is used to create b, where the values: 2,3,-1 in the call means:
Create 2 matrixes, each having 3 rows, adjust the number of columns to match the data (-1)
In this case we get b.shape = (2,3,5)
Theese dimensions correspond to axes/dimensions 0, 1, 2, that are used to perform calculations or extract data.
E.g. 
b[0] brings the element for the first dimension: matrix 1.
b[:,0] gives the first row for matrix 1 and 2.
b[1,:,3] gives the fourth column of the matrix in the second group
For calculations - the axis 0,1,2 determine how these are performed. In our case:
b.mean(axis=0) means that the answer will be shaped (3,5) 
    -The mean value of b[0,:,:] and b[1,:,:]... So the answer is one matrix
b.mean(axis=1) means that the answer will be shaped(2,5) -First row mean values for matrix1, second for matrix 2
    -The mean value over each column for each matrix (values added vertically)
b.mean(axis=2) means that the answer will be shaped(2,3) - First row for matrix 1, second for matrix 2
    -The mean value over each row for each matrix (values added horisontally)

**

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [30]:
def add_mult_matrices(mat_1, mat_2, /, calc_method):
    if isinstance(mat_1, np.ndarray) and isinstance(mat_2, np.ndarray):
        if calc_method.lower() == "add":
            if mat_1.shape == mat_2.shape:
                print("The result of the addition is \n",
                mat_1 + mat_2)
            else:
                print("Matrices need to be of same size when choosing addition!")
                
        elif calc_method.lower() == "multiply":
            if mat_1.shape[1] == mat_2.shape[0]: # checks if matrix multiplication is possible
                 print("The result of the matrix multiplication is \n",
                mat_1 @ mat_2)
            else:
                print("Matrix multiplication not possible. Ensure that #columns in matrix 1 equals #rows in matrix 2")
        else:
            print("Please type in 'add' for addition, or 'multiply' for multiplication!")
    else: 
        print("Both arrays need to be a numpy array")

In [70]:
# Here we can test my function above with addition of matrices
# Addition works fine when correct size of matrices
m1 = np.arange(1, 10).reshape(3,3)
m2 = np.arange(21, 30).reshape(3,3)

print(m1)
print(m2)
add_mult_matrices(m1, m2, "multiply")

#Doesn't work when m1 and m2 hasn't the correct dimensions
# m1 = np.arange(1, 21).reshape(2,10)
# m2 = np.arange(21, 30).reshape(3,3)
# add_mult_matrices(m1, m2, "ADD")

# Check case  [[]]



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]
The result of the matrix multiplication is 
 [[150 156 162]
 [366 381 396]
 [582 606 630]]


In [33]:
# Here we can test my function above with matrix multiplication

# Matrix multiplication works fine when correct dimensions 
m1 = np.arange(1, 7).reshape(3,2)
m2 = np.arange(21, 27).reshape(2,3)
print(m1)
print(m2)
add_mult_matrices(m1, m2, "multiply")

# Doesn't work well when m1.shape[1] != m2.shape[0]
# m1 = np.arange(1, 7).reshape(3,2)
# m2 = np.arange(0, 16).reshape(4,4)
# print(m1)
# print(m2)
# add_mult_matrices(m1, m2, "multiply")


[[1 2]
 [3 4]
 [5 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Matrix multiplication not possible. Ensure that #columns in matrix 1 equals #rows in matrix 2


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [42]:
# Solved by programming - I solved it by hand too.

#10.1.1
print("10.1.1")
x = np.array([4,3])
#a -dimension
# The dimension of x is 1x2 - numpy sees it as a 1D though. x = np.array([[4,3]]) makes it have the 1x2 shape here..

#b 5x is:
print("b)",5*x)

#c 3x is:
print("c)",3*x)

#d 5x + 3x is:
print("d)",5*x+3*x)

#e 8x is:
print("e)",8*x)

#f 4x-x is:
print("f)",4*x-x)

#g x transposed is not visually obtainable when x defined as above. 
#correct dimension for x transposed is 2x1.
print("g)",x.T)

#h x + x transposed is:
print("h)",x+x.T, " which is incorrect, arrays must have equal size when adding") 

#i norm of x
print("i)", np.linalg.norm(x))

print("10.1.2")
v = np.array([3, 7, 0, 11]) # v defined in 1D

# a) the dimension for v is 4x1

# task b-d the result presented in 1D... mathematical they are in 4x1-shape!
#b 2v is: 
print("b)",2*v) 

#c 5v+2v is: 
print("c)",5*v+2*v)

#d 4v-2v is: 
print("d)",4*v-2*v)

#e v transposed is not visually obtainable when v defined as above. 
#correct dimension for v transposed is 1x4.
print("e)",v.T)

#f norm of v
print("f)", np.linalg.norm(v))

print("10.1.3")

#10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
#a norm of v1
print("a)", np.linalg.norm(v1))

#b norm of v1
print("b)", np.linalg.norm(v1-v2))




10.1.1
b) [20 15]
c) [12  9]
d) [32 24]
e) [32 24]
f) [12  9]
g) [4 3]
h) [8 6]  which is incorrect, arrays must have equal size when adding
i) 5.0
10.1.2
b) [ 6 14  0 22]
c) [21 49  0 77]
d) [ 6 14  0 22]
e) [ 3  7  0 11]
f) 13.379088160259652
10.1.3
a) 7.14142842854285
b) 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [44]:
A = np.array([[2, 1, -1],[1, -1, 1]])
B = np.array([[4, -2, 1],[2, -4, -2]])
C = np.array([[1, 2],[2, 1]])
D = np.array([[3, 4],[4, 3]])
E = np.array([[1],[2]])
I = np.array([[1, 0],[0, 1]])
A.T @ D

array([[10, 11],
       [-1,  1],
       [ 1, -1]])

In [113]:
# Made the tasks with pen an paper, and here..
print("10.2.1")
A = np.array([[2, 1, -1],[1, -1, 1]])
B = np.array([[4, -2, 1],[2, -4, -2]])
C = np.array([[1, 2],[2, 1]])
D = np.array([[3, 4],[4, 3]])
E = np.array([[1],[2]])
I = np.array([[1, 0],[0, 1]])
# print("A: ",A)
# print("B: ",B)
# print("C: ",C)
# print("D: ",D)
# print("E: ",E)
# print("I: ",I)

#(a) 2A
print("a)",2*A)

# (b) B − 2A
print("b)",B-2*A)

# (c) 3C − 2E
print("c)",3*C-2*E, "mathematically not possible. Here ok due to broadcasting")

# (d) 2D − 3C
print("d)",2*D-3*C)

# (e) D⊤ + 2D
print("e)",D.T + 2*D)

# (f) 2C⊤ − 2D⊤
print("f)", 2*C.T@(2*D.T))

#  (g) A⊤ − B
print("g) Not possible due to different shapes.")

# # (h) AC
print("h) Not possible due to #colums in A != #rows in B")

# # (i) CD
print("i)",C @ D)

# (j) CB
print("j)",C @ B)

# (k) CI
print("k)",C @ I)

# (l) AB⊤
print("l)",A @ B.T)

10.2.1
a) [[ 4  2 -2]
 [ 2 -2  2]]
b) [[ 0 -4  3]
 [ 0 -2 -4]]
c) [[ 1  4]
 [ 2 -1]] mathematically not possible. Here ok due to broadcasting
d) [[3 2]
 [2 3]]
e) [[ 9 12]
 [12  9]]
f) [[44 40]
 [40 44]]
g) Not possible due to different shapes.
h) Not possible due to #colums in A != #rows in B
i) [[11 10]
 [10 11]]
j) [[  8 -10  -3]
 [ 10  -8   0]]
k) [[1 2]
 [2 1]]
l) [[5 2]
 [7 4]]


In [119]:
#10.2.2 
A = np.array([[2, 3, 4],[5, 4, 1]])
print("A x A.t is: \n", A @ A.T)

A x A.t is: 
 [[29 26]
 [26 42]]


In [120]:
#10.2.3
A = np.array([[1, 2],[2, 4]])
B = np.array([[2, 1],[1, 3]])
C = np.array([[4, 3],[0, 2]])
print("AB equals AC:\n", (A @ B) == (A @ C))
print("B doesn't equal C: \n", B == C)



AB equals AC:
 [[ True  True]
 [ True  True]]
B doesn't equal C: 
 [[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [56]:
# If we change v1, v2 will change as well if it's a view, otherwise it's a copy

v1 = np.arange(4)
#v2 = v1.reshape(2,2)
v2 = v1[-2:] #Slicing - the second value from end to end.
print(v1)
print(v2)

v1[-1] = 123 #No copy/view. Assignment happens in place

print(v1)
print(v2)

# Since v2 changed when we did the change to v1 - v2 is a view.

#The base attribute can be used to check whether an array is a view or a copy of an array

if v2.base is v1:
    print("The operation above created a view.")
else:
    print("The operation above created a copy.")


[0 1 2 3]
[2 3]
[  0   1   2 123]
[  2 123]
The operation above created a view.


In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)